name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm install

    - name: Make Capacitor CLI executable
      run: chmod +x node_modules/.bin/cap

    - name: Sync Capacitor project
      run: npx cap sync android

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build Android debug APK
      run: cd android && ./gradlew assembleDebug --stacktrace --info

    - name: List APK contents
      run: ls -la android/app/build/outputs/apk/debug/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
